---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider
    - path: compact-bar
      tag: compact-bar

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
# default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
#pane_frames: true

themes:
  catppuccin-latte:
    bg: "#acb0be" # Surface2
    fg: "#acb0be" # Surface2
    red: "#d20f39"
    green: "#40a02b"
    blue: "#1e66f5"
    yellow: "#df8e1d"
    magenta: "#ea76cb" # Pink
    orange: "#fe640b" # Peach
    cyan: "#04a5e5" # Sky
    black: "#4c4f69" # Text
    white: "#dce0e8" # Crust

  catppuccin-frappe:
    bg: "#626880" # Surface2
    fg: "#c6d0f5"
    red: "#e78284"
    green: "#a6d189"
    blue: "#8caaee"
    yellow: "#e5c890"
    magenta: "#f4b8e4" # Pink
    orange: "#ef9f76" # Peach
    cyan: "#99d1db" # Sky
    black: "#292c3c" # Mantle
    white: "#c6d0f5"

  catppuccin-macchiato:
    bg: "#5b6078" # Surface2
    fg: "#cad3f5"
    red: "#ed8796"
    green: "#a6da95"
    blue: "#8aadf4"
    yellow: "#eed49f"
    magenta: "#f5bde6" # Pink
    orange: "#f5a97f" # Peach
    cyan: "#91d7e3" # Sky
    black: "#1e2030" # Mantle
    white: "#cad3f5"

  catppuccin-mocha:
    bg: "#585b70" # Surface2
    fg: "#cdd6f4"
    red: "#f38ba8"
    green: "#a6e3a1"
    blue: "#89b4fa"
    yellow: "#f9e2af"
    magenta: "#f5c2e7" # Pink
    orange: "#fab387" # Peach
    cyan: "#89dceb" # Sky
    black: "#181825" # Mantle
    white: "#cdd6f4"

theme: catppuccin-frappe

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
#mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
#copy_clipboard: primary

# Enable or disable automatic copy (and clear) of selection when releasing mouse
#copy_on_select: true

# Path to the default editor to use to edit pane scrollbuffer
# scrollback_editor: /usr/bin/nano
